siteTitle = "Scaphold"
baseColor = "#1DAAA0"
baseUrl = "https://scaphold.io"
linkPrefix = "/community"
googleAnalyticsId = "UA-87284467-1"
blogPosts = [
  "/blog/send-push-notifications-scaphold-graphql/",
  "/blog/iOS-push-notifications-with-graphql/",
  "/blog/android-push-notifications-with-graphql/",
  "/blog/apollo-optics-and-your-graphql-server/",
  "/blog/algolia-powers-thousands-of-scaphold-apps/",
  "/blog/authentication-in-graphql/",
  "/blog/querying-relational-data-with-graphql/",
  "/blog/initial-impressions-scaphold/",
  "/blog/aggregations-in-graphql/",
  "/blog/migrate-mongodb-to-graphql/",
  "/blog/introduction-logic/",
  "/blog/scaphold-2016-year-in-review/",
  "/blog/build-realtime-apps-with-subs/",
  "/blog/state-of-graphql/",
  "/blog/build-better-websites-with-angular2-and-graphql/",
  "/blog/payments-api-with-graphql/",
  "/blog/pokemon-go-graphql-with-aws-lambda/",
  "/blog/social-auth-graphql/",
  "/blog/fastest-way-to-get-started/",
  "/blog/graphql-hacks/",
  "/blog/scaphold-introduction/"
]
